# Generated by Django 5.0.4 on 2024-04-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='package',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
